version: "3.7"

services:
  react-app:
    container_name: react-dev
    image: node
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    working_dir: /usr/src/app
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run dev
